### ISSUE TITLE
Pendências do sistema Gestão Projetos

### ISSUE THREAD

**Issue by IslaGuedes** [IslaGuedes/GestaoProjetos#22]
• Erro ao adicionar telefone em Aluno e Orientador.

• Falta Validações dos campos de todas as telas. 

•  Cadastro de PROJETOS.

• Relatórios.

• LOGIN do sistema

• Erros nas Telas:
- template admin tem que herdar de template externo;
- Imagem de simbolo do IFNMG não aparece em template ADMIN.

**Comment by petroniocandido** [comment]
Você deve criar uma issue separada para cada pendência.
