### ISSUE TITLE
Criar o TemplateExterno

### ISSUE THREAD

**Issue by IslaGuedes** [IslaGuedes/GestaoProjetos#4]
O template externo será utilizado pelas páginas sem autenticação: as páginas de login, cadastro e novasenha.

O template deverá conter apenas um cabeçalho com a logomarca do IFNMG e o nome d sistema, e no rodapé informações sobre o desenvolvedor.

**Comment by petroniocandido** [comment]
Retirar o menu do TemplateExterno
